import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from "../components/Header"
import Banner from "../components/Banner"

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Skyscanner</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/skyscanner-logo.png" />
      </Head>

      <Header/>
      <Banner/>
    </div>
  )
}

export default Home
